# This is a basic workflow to help you get started with Actions

name: PHP Branch Push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ php/* ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    
    - name: upload php to /test
      uses: garygrossgarten/github-action-scp@release
      with:
        local: Website/src/PHP
        remote: public_html/test/${{ steps.extract_branch.outputs.branch }}
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
      
    - name: upload css
      uses: garygrossgarten/github-action-scp@release
      with:
        local: Website/src/css
        remote: public_html/test/php/css
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
      
    - name: setting permissions
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd public_html/test/${{ steps.extract_branch.outputs.branch }}
          chmod 600 *.php
          ls -l
          cd ..
          cd css
          ls -l

